/*
 * Elementals - Rachel
 * this is the form that will ask random question quizzes about the earth topic
 */
package elementals;

//imports for the program
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.Random;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author rachelroutly
 */
public class earth extends javax.swing.JFrame {
    //global variables for character and referenced forms
    player character;
    home house;
    training train;
    
    /**
     * Creates new form earth
     * @param c
     */
    public earth(player c) {
        initComponents();
        //set back ground colouring
        Color train = new Color(255,249,165);
        this.getContentPane().setBackground(train);
        character = c;
        //calls the method to choose questions and sets the value of the text to the earth value
        chooseQuestions();
        earthVal.setText(String.valueOf(character.getEarth()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        earthVal = new javax.swing.JLabel();
        homeBttn = new javax.swing.JButton();
        questionOne = new javax.swing.JLabel();
        questionTwo = new javax.swing.JLabel();
        questionThree = new javax.swing.JLabel();
        answerOne = new javax.swing.JComboBox<>();
        answerTwo = new javax.swing.JComboBox<>();
        answerThree = new javax.swing.JComboBox<>();
        submitBttn = new javax.swing.JButton();
        skipOne = new javax.swing.JButton();
        skipTwo = new javax.swing.JButton();
        skipThree = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elementals/images/earth-icon.png"))); // NOI18N
        jLabel1.setText("  :");

        earthVal.setText("       ");

        homeBttn.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N
        homeBttn.setText("Back to Home");
        homeBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBttnActionPerformed(evt);
            }
        });

        questionOne.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N
        questionOne.setText(" --");

        questionTwo.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N
        questionTwo.setText(" --");

        questionThree.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N
        questionThree.setText(" --");

        answerOne.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N

        answerTwo.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N

        answerThree.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N

        submitBttn.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N
        submitBttn.setText("Submit");
        submitBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBttnActionPerformed(evt);
            }
        });

        skipOne.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N
        skipOne.setText("Skip");
        skipOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipOneActionPerformed(evt);
            }
        });

        skipTwo.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N
        skipTwo.setText("Skip");
        skipTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipTwoActionPerformed(evt);
            }
        });

        skipThree.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N
        skipThree.setText("Skip");
        skipThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipThreeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(earthVal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(questionOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(questionTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(questionThree, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 360, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(answerThree, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(skipThree, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(answerOne, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(skipOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(answerTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(skipTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(submitBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(homeBttn, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(earthVal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionOne)
                    .addComponent(answerOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(skipOne))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answerTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(skipTwo))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionThree)
                    .addComponent(answerThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(skipThree))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(submitBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeBttn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBttnActionPerformed
        // closes the current form, and opens the home form
        if(house == null){
            house = new home(character);
        }
        this.setVisible(false);
        house.setVisible(true);
    }//GEN-LAST:event_homeBttnActionPerformed
    //variable to track the number of correct answers
    int numCorrect = 0;
    //checks which questions were skipped to ensure that points aren't counter twice
    boolean skipped1 = false;
    boolean skipped2 = false;
    boolean skipped3 = false;
    private void submitBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBttnActionPerformed
        //if the selected item is the same as the correct answer at the same index of the correct array the numCorrect increases 
        if((correct[numOne] == answerOne.getSelectedItem()) && skipped1 == false){
            numCorrect++;
        }
        //checks for correct again
        if((correct[numTwo] == answerTwo.getSelectedItem()) && skipped2 == false){
            numCorrect++;
        }
        //checks for correct again
        if((correct[numThree] == answerThree.getSelectedItem()) && skipped3 == false){
            numCorrect++;
        }        
        //gets the earth value
        double e = character.getEarth();
        //creates a new decimal format to save values to two decimals
        DecimalFormat numberFormat = new DecimalFormat("0.0");
        //adds the correct amount to the character's earth value
        switch (numCorrect) {
            case 1:
                character.setEarth(Double.parseDouble(numberFormat.format(e + 0.3)));
                break; 
            case 2:
                character.setEarth(Double.parseDouble(numberFormat.format(e + 0.6)));
                break;
            case 3:
                character.setEarth(Double.parseDouble(numberFormat.format(e + 1.0)));
                break;
            default:
                break;
        }
        //gives the user a message of how many questions they ansswered correctly
        JOptionPane.showMessageDialog (null, "You Answered " + numCorrect + " Question(s) Correctly", "Not Allowed", JOptionPane.INFORMATION_MESSAGE);
        //closes current form and opens training form 
        if(train == null){
            train = new training(character);
        }
        this.setVisible(false);
        train.setVisible(true);
    }//GEN-LAST:event_submitBttnActionPerformed

    private void skipOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipOneActionPerformed
        // calls the skipQuestion method
        skipQuestion();
        skipped1 = true;
        skipOne.setEnabled(false);
    }//GEN-LAST:event_skipOneActionPerformed

    private void skipTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipTwoActionPerformed
        // calls the skipQuestion method
        skipQuestion();
        skipped2 = true;
        skipTwo.setEnabled(false);
    }//GEN-LAST:event_skipTwoActionPerformed

    private void skipThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipThreeActionPerformed
        // calls the skipQuestion method
        skipQuestion();
        skipped3 = true;
        skipThree.setEnabled(false);
    }//GEN-LAST:event_skipThreeActionPerformed
//global variables for the question and answer arrays 
String[] questions = {"The climate is made of five components, which relates to rocks and sediments?", 
                          "Offshore earthquakes can cause ________", 
                          "______% of the energy in an earthquake is seismic", 
                          "Which is not a normal type of fault", 
                          "Earthquales from normal faults generally have a magnitude less than ______", 
                          "An 8.6 magnitude earthquake releases the same energy as _______ bombs from WW2", 
                          "How many major tectonic plates are there?", 
                          "How many minor tectonic plates are there?",
                          "Which is not a classification of tectonic plate?",
                          "What is the minimum amount of time to form 1 inch of top soil?",
                          "There are _______ different types of soil in the US", 
                          "What type of tree changes the acidity of its soil to prevent other growth?", 
                          "In a _________ of healthy soil there are more organisms than humans on earth.",
                          "In North America (as of 2003) ______ soil series have gone extinct",
                          "Which is not a common threat to soil health?"};
    
    String[] correct = {"lithosphere",
                        "tsunamis",
                        "10",
                        "horizontal",
                        "7",
                        "10,000",
                        "7",
                        "10",
                        "nano",
                        "500 years",
                        "70,000",
                        "Black Walnut",
                        "Teaspoon",
                        "33",
                        "Over Watering"};
    
    String[] wrong1 =  {"atmosphere",
                        "hurricanes",
                        "10",
                        "normal",
                        "2",
                        "100",
                        "10",
                        "7",
                        "major",
                        "10 years",
                        "10,000",
                        "Oak",
                        "Litre",
                        "4",
                        "Urbanization"};
    
    String[] wrong2 =  {"cryosphere",
                        "tornados",
                        "50",
                        "reverse",
                        "13",
                        "1,000",
                        "18",
                        "8",
                        "minor",
                        "50 years",
                        "30,000",
                        "Cherry",
                        "Cup",
                        "27",
                        "Acidification"};
    
    String[] wrong3 =  {"biosphere",
                        "hail",
                        "85",
                        "strike-slip",
                        "9",
                        "1",
                        "5",
                        "19",
                        "micro",
                        "100 years",
                        "90,000",
                        "Maple",
                        "Tablespoon",
                        "46",
                        "Overgrazing"};
    
    //sets random numbers for 1-3 (used for choosing/finding questions)
    Random rand = new Random(); 
    int numOne = rand.nextInt((15 - 1) + 1) + 1;
    int numTwo = rand.nextInt((15 - 1) + 1) + 1;
    int numThree = rand.nextInt((15 - 1) + 1) + 1;
    
    //chooses three question and calls the random order method
    public void chooseQuestions(){           
        questionOne.setText(questions[numOne]);
        ranOrder(numOne, answerOne);
        
        questionTwo.setText(questions[numTwo]);
        ranOrder(numTwo, answerTwo);
        
        questionThree.setText(questions[numThree]);
        ranOrder(numThree, answerThree);
    }
    
    //randomizes the order of the answers
    public void ranOrder(int n, JComboBox<String> question){
        //makes a random number between 1 and 4, that will indicated which of the four slots the correct answer should be in
        int order = rand.nextInt((4 - 1) + 1) + 1;
        //if it is 1 --> first slot, 2 --> second slot and so on
        if(order <= 1){
            question.addItem(correct[n]);
            question.addItem(wrong1[n]);
            question.addItem(wrong2[n]);
            question.addItem(wrong3[n]);
        }   
        else if(order <= 2){           
            question.addItem(wrong1[n]);
            question.addItem(correct[n]);
            question.addItem(wrong2[n]);
            question.addItem(wrong3[n]);
        } 
        else if(order <= 3){
            question.addItem(wrong1[n]);           
            question.addItem(wrong2[n]);
            question.addItem(correct[n]);
            question.addItem(wrong3[n]);
        }
        else{
            question.addItem(wrong1[n]);            
            question.addItem(wrong2[n]);
            question.addItem(wrong3[n]);
            question.addItem(correct[n]);
        }       
    }
    //handles the clicking of the skip question button
    public void skipQuestion(){
        //gets the XP value of the character
        int xpValue = character.getXP();
        //if they have more than 1 xp, the number of correct answers increases by one, and the xp value drops by 1
        if(xpValue >= 1){
            character.setXP(xpValue - 1);
            numCorrect++;
        }
        //if not they are notified with a pop up message
        else{
            JOptionPane.showMessageDialog (null, "You Don't Have Enough XP to Skip a Question", "Not Allowed", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> answerOne;
    private javax.swing.JComboBox<String> answerThree;
    private javax.swing.JComboBox<String> answerTwo;
    private javax.swing.JLabel earthVal;
    private javax.swing.JButton homeBttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel questionOne;
    private javax.swing.JLabel questionThree;
    private javax.swing.JLabel questionTwo;
    private javax.swing.JButton skipOne;
    private javax.swing.JButton skipThree;
    private javax.swing.JButton skipTwo;
    private javax.swing.JButton submitBttn;
    // End of variables declaration//GEN-END:variables
}
