/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elementals;

import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author rachelroutly
 */
public class gameOver extends javax.swing.JFrame {
    start starter;
    player character;
    home house;
    /**
     * Creates new form gameOver
     */
    public gameOver(player c) {
        initComponents();
        character = c;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        saveBttn = new javax.swing.JButton();
        endBttn = new javax.swing.JButton();
        exitBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel1.setText("Game Over");

        saveBttn.setText("Save Life for 6 XP");
        saveBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBttnActionPerformed(evt);
            }
        });

        endBttn.setText("Back to Start");
        endBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endBttnActionPerformed(evt);
            }
        });

        exitBttn.setText("Close Game");
        exitBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(saveBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(endBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(saveBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endBttn)
                    .addComponent(exitBttn))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBttnActionPerformed
        // TODO add your handling code here:
        File origFile = new File("src//elementals//character_saves//" + character.getUserName() + ".txt"); 
        origFile.delete();
        
        System.exit(0);
    }//GEN-LAST:event_exitBttnActionPerformed

    private void endBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endBttnActionPerformed
        // TODO add your handling code here:
        File origFile = new File("src//elementals//character_saves//" + character.getUserName() + ".txt"); 
        origFile.delete();
        
        this.setVisible(false);
        
        start starter = new start();
        starter.setVisible(true); 
    }//GEN-LAST:event_endBttnActionPerformed

    private void saveBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBttnActionPerformed
        // TODO add your handling code here:
        int xpValue = character.getXP();
        if(xpValue >= 6){
            character.setXP(xpValue - 6);
            if(house == null){
                System.out.println("test");
                house = new home(character);
            }    
            this.setVisible(false); 
            house.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog (null, "You Don't Have Enough XP to Save Life", "Not Allowed", JOptionPane.INFORMATION_MESSAGE);
            File origFile = new File("src//elementals//character_saves//" + character.getUserName() + ".txt"); 
            origFile.delete();
            
            this.setVisible(false);
        
            start starter = new start();
            starter.setVisible(true); 
        }
    }//GEN-LAST:event_saveBttnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton endBttn;
    private javax.swing.JButton exitBttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton saveBttn;
    // End of variables declaration//GEN-END:variables
}
